### ISSUE TITLE
skills containing required slots

### ISSUE THREAD

**Issue by mskaufland** [ExpediaDotCom/alexa-conversation#12]
If a skill contains required slots, inserted via the skill-builder the tests fail, because there is no local fulfillment for this. Is there an easy way to mock such skill-builder-features with alexa-conversation?

**Comment by gamell** [comment]
Hi @mskaufland , sorry but I haven't used the skill-builder, could you paste an example here so I know what format you are talking about? Thanks!

**Comment by gamell** [comment]
I will close this for now as it's stale. Reopen if you want to provide more info.
