### ISSUE TITLE
Remove npm-shrinkwrap

### ISSUE THREAD

**Issue by mithun** [ExpediaDotCom/alexa-conversation#13]
Please remove npm-shrinkwrap or use [shrinkydink](https://www.npmjs.com/package/shrinkydink) to remove all URLs resolved to NPM Registry.

This prevents package consumers from using a custom NPM registry

**Comment by gamell** [comment]
Solved in v0.2.0 - https://github.com/ExpediaDotCom/alexa-conversation/releases/tag/v0.2.0
