### ISSUE TITLE
alexa conversation will work if the skill is developed in go lang

### ISSUE THREAD

**Issue by rsmamidi** [ExpediaDotCom/alexa-conversation#14]
hi,

if the Alexa skill is developed in golang will the the frame work will help to automate, if yes can you share some sample project will clear steps for using it

**Comment by gamell** [comment]
Hi there, sadly this only works with nodejs skills as it imports your skill's handler and calls it directly. If you wanted to make this framework compatible with other languages you'd have to build some module to make this framework communicate with skills running on remote servers which could be implemented in any language.
