### ISSUE TITLE
Handler STATE

### ISSUE THREAD

**Issue by ellier** [ExpediaDotCom/alexa-conversation#7]
Forgive me if I'm wrong, but I don't see a way to deal with different states.
I'm talking about this:

`Alexa.CreateStateHandler(States.READY, {
 // handlers here
})`

**Comment by gamell** [comment]
Hi @ellier forgive me if I am missing something - we decided not to use the state feature of the Amazon Alexa SDK ourselves - but I think what you are talking about will be determined by what intents you trigger in the conversation.

For example, when you start the conversation, I guess you will be in the `STARTMODE` state, and from there you can 'navigate' to the desired state by triggering the correct intents:

```js
conversation(opts).
   .userSays('someIntent') // this will trigger the internal logic of your Alexa skill, which will follow your defined states.
   .userSays('someOtherIntent')
   ...
```

Again, please let me know if I'm missing something.
