### ISSUE TITLE
Custom Handler Name

### ISSUE THREAD

**Issue by seanfisher** [ExpediaDotCom/alexa-conversation#8]
My module exports multiple handlers with names other than the default `handler`. Can an option be added to the `options` to specify a custom handler name?

**Comment by gamell** [comment]
Hi @seanfisher . Sure, are you talking about something like this?

```js
const opts = {
  ...
  handlerName: 'customName',
  ...
};
```

I think passing the handler directly into the conversation would be cleaner and more concise, and would solve your problem:

```js
conversation({ name: 'name', handler: app.customHandler, ...);
```
For backward compatibility, if no `handler` is passed, we could call `app.handler`

**Comment by seanfisher** [comment]
Yeah, that's a great idea. It'll probably be easier to implement passing the handler itself rather than trying to dynamically call a function based on a string name anyway.
